### ISSUE TITLE
Hardware question

### ISSUE THREAD

**Issue by smithan7** [MISTLab/XbeeMav#1]
First, thanks for pushing this, great.

Which XBees are you using with the M100 and how well did they work / what kind of range were you able to get? Also, what type of on-board processing are you using? I have the M100 with Jetson TX2 and am trying to figure out how I want to communicate between team members.

**Comment by dastoqc** [comment]
Hi.

Thanks for your question and your interest in our work. We are using Xbee Pro 900Mhz modules, not the fastest, but providing the longest range. We did not yet extensively tested their potential, but we managed to achieve workable communication up to at least 500m with standard antenna. It greatly depends on your network configuration. The communication node is really not demanding. We deployed it on TK1 and TX1, so your TX2 will not even notice the node is running. It was tested with ROS Indigo on Ubuntu 14.04 and Kinetic on Ubuntu 16.04, but it should work just fine on earlier versions.

Hope this helps. Please give us feedback if you deploy this node in your setup.
