### ISSUE TITLE
InMavlink topic & Baud rate[8]

### ISSUE THREAD

**Issue by JonyYun-Kim** [MISTLab/XbeeMav#2]
Hi!
Thanks for providing your work :)

I have two questions.
**1. I can't echo InMavlink topic**
  - "xbeemav.launch" file shows the loaded device on the computer and Drone&run_mode types. 
But I can't echo InMavlink topic. I'm using test_buzz node to check the communication.
I sent test_buzz messages on another xbee device connected to another computer.
I can see the devices blinking TX(or RX) LED while sending the messages(ros_buzz). Considering the timing and time of blinking LED, it seems the xbee devices are communicating.

**2. xbee device configure to baud rate [8] (230400) seems not to work**
  - If I configure a xbee device with baud rate 230400, it seems that the computer won't accept(?) the xbee device. I mean, the launch file doesn't show any information of the device and can't see the topic either.

I'm using Xbee pro digimesh 2.4 (XBP-24DM) with sparkfun xbee explorer dongle on ubuntu 16.04 (ROS Kinetic)

thanks in advance!!

**Comment by dastoqc** [comment]
Hi.

Thank you for your feedback. First off, we never tried it with your Xbee model, we used only Xbee 900Mhz Pro. On the other hand, we did tested it on Ubuntu 16/Kinetic and with the Sparkfun dongle. Are you sure your device accepts this baudrate?

You are making a good point about the test_buzz node... been a while we haven't tested it, and it may not be compatible with latest changes. I'll try to have a look at it this week. Nevertheless, the rosbuzz node should start sending and receiving mavlink payload at launch (on both computer).

Cheers.

**Comment by JonyYun-Kim** [comment]
thanks for your reply!

Few days ago, I ordered Xbee 900Mhz Pro model you used. So I might be able to use the xbee model in a while.

I thought my device seemed to accept the baud rate(230400) when I configure the device. Because there was no error at the configuration step. (Once it is configured to 230400, it is never configured into any other configuration unless I reset firmware of the device )  But I should check whether it really gets the baud rate.
I couldn't check the baud rate at XCTU parameter of the device because 230400 is not the standard baud rate for the model. On the other hand, the Port name of the device showed the baud rate in XCTU (e.g. /dev/ttyUSB0 - 230400/8N/1/N - API 1)

As you said, I think I'd better do the test with rosbuzz node instead of test_buzz node.
